osx_image: 
  - xcode9.3
  - xcode10.1
  - xcode10.2

language: objective-c

script:
  - set -o pipefail && xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace XCTestHTMLReport.xcworkspace -scheme XCTestHTMLReport -configuration Release | xcpretty
  - ./xchtmlreport -h